---

---

###Methods of Analysis

Coming from the world of chemistry I strongly believe that lab work is about fine tuning rather than about simply generating a result. To that end I am trying to publish reproducable methods with pro tips on this site. Comments, questions, and criticsm are all welcome!  

Below I try to briefly introduce why one would go about measuring something, and then a link is provided to tell you everything I know about making the right decisions to get an accurate measurement with both anecdotal and literature based references were possible.

#####First, some notes on design.
It is important to think about where variability lies in an experiment and sample accordingly. To help decide how many samples to take, consider using an **a priori test of statistical power** to estimate sample sizes that will be required. A short tutorial with R code is found [here](power.html).  

Then, comes design! I certainly can't provide a comprehensive list, but a few common field designs are mentioned in brief [here](design.html)

#####Soil Texture Analysis
There are many reasons people measure soil texture. Some basic interests include links to hydrologic properties within and between layers, i.e. drainage, storage, and their kinetics. Also, carbon and nutrient storage and cycling, and microbial activity are all interdependent and often relate to the ability of a soil to store available nutrients and water. There is a 'goldilocks' zone where there is enough surface area to store nutrients and water, while still allowing some active movement and cylcing, rather than immobilizing soil water and nutrient flows. There are many methods for measuring soil texture, most common are hydrometer and pipette methods described [here](texture.html). Additionally particle size analyzers are commercially available which use [laser diffraction](https://en.wikipedia.org/wiki/Laser_diffraction_analysis).

#####Soil Iron and Aluminum Mineralogy
Important for mineralogical analysis, and selective dissolution of different mineral forms of iron and aluminum. This method is growing in use and popularity for evaluating soil carbon storage potentia because of recently published work that suggests soil mineral characteristics may better predict carbon storage/potential than more classic concepts (i.e. texture). Methods [here](files/Soil_iron_assays.pdf).

###Coming soon...



#####Soil Avalable Water Capacity

#####Soil Bulk Density

#####Soil pH

#####Soil Nitrate and Ammonium Analysis

#####Soil/plant Phosphorous Analysis

#####Total Carbon and Nitrogen Analysis

#####Soil Lipid Fractionations

#####Cellulose Extraction from plant tissue

#####Accessing SSURGO Data in R

#####MODIS/TERRA bulk extraction of data in R

#####Basic use of Google Earth Engine for Time Series Analysis

#####Trace Gas sampling protocols

#####Leaf Area Index