  

&nbsp;   
  
### Recent Publciations

**Maxwell, T.M.**, Germino, M.J., Romero, S., Porensky, L., Blumenthal, D., Adler, P. (In prep) Climate variability introduced by manipulated soil-surface albedo affects phenology and growth of cheatgrass. Target Journal: Rangeland Ecology and Management.

**Maxwell, T.M.**, Germino, M.J. (In review). The effects of cheatgrass invasion on US Great Basin carbon storage depend on interactions between plant community composition, precipitation seasonality, and soil climate regime. Journal of Applied Ecology.

Dawson, H.R., **Maxwell, T.M.**, Reed, P. B., Bridgham, S., and Silva, L.C.R. (In Review) Plant form- function relationships predict water-use efficiency under experimental drought in grasslands. Journal of Experimental Botany.

Renwick, L.L.R., Deen, W.,Silva, L.C.R., Gilbert, M.E., **Maxwell, T.M.**, Bowles, T.M., Gaudin, A.C.M. (2021). Long-term crop rotation diversification enhances maize drought resistance through soil organic matter. Environmental Research Letters. [doi: 10.1088/1748-9326/ac1468](https://doi.org/10.1088/1748-9326/ac1468)

Broz, A., Retallack, G.J., **Maxwell, T.M.** and Silva, L.C.R, (2021). A record of vapour pressure deficit preserved in wood and soil across biomes. Nature Scientific Reports.[doi:10.1038/s41598-020-80006-9](https://doi.org/10.1038/s41598-020-80006-9)

**Maxwell T. M.**, Silva L.C.R. (2020) A State Factor Model for Ecosystem Carbon – Water Relations. Trends in Plant Science.[doi:10.1016/j.tplants.2020.02.007](https://www.sciencedirect.com/science/article/abs/pii/S136013852030056X)

Liles, G.C., **Maxwell T. M.**, Silva L.C.R., Zhang, J., Horwath W.R.H. (2019) Two decades of experimental manipulation reveal potential for enhanced biomass accumulation in ponderosa pine plantations across climate gradients. J. Geophys. Res Biogeosciences. [doi: 10.1029/2019JG005183](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JG005183)

**Maxwell T.M.**, Silva L.C.R., Horwath W.R. (2018) Predictable oxygen isotope exchange between plant lipids and environmental water: implications for ecosystem water balance reconstruction. J. Geophys. Res Biogeosciences. [doi:10.1029/2018JG004553](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2018JG004553).

**Maxwell, T.M.**, Silva, L.C.R. & Horwath, W.R. (2018). Integrating effects of species composition and soil properties to predict shifts in montane forest carbon–water relations. Proc. Natl. Acad. Sci. [doi:10.1073/PNAS.1718864115](http://www.pnas.org/content/early/2018/04/13/1718864115.full)

Jerszurki, D. Couvreur, V., **Maxwell, T.M.**, Silva, L.C.R., Matsumoto, N., Shackel, K., de Souza, J.L.M., Hopmans, J. (2017). Impact of root growth and hydraulic conductance on canopy carbon-water relations of young walnut trees (Juglans regia L.) under drought. Sci. Hortic. (Amsterdam). 226. [doi:10.1016/j.scienta.2017.08.051](https://www.sciencedirect.com/science/article/pii/S0304423817305216)

**Maxwell, T. M.**, Silva, L. C. R. & Horwath, W. R. (2014). Using multielement isotopic analysis to decipher drought impacts and adaptive management in ancient agricultural systems. Proc. Natl. Acad. Sci. 2–3. [doi:10.1073/pnas.1417618111](http://www.pnas.org/content/111/45/E4807.full)
